#!/bin/bash
# Ralph Wiggum - AI Loop Technique for Claude Code
# "I'm helping!" - Ralph Wiggum
#
# Usage: ./ralph.sh [options] "Your prompt"
# See --help for full options

set -e

# Default values
MAX_ITERATIONS=50
COMPLETION_PROMISE="COMPLETE"
PROMPT_FILE=""
WORKING_DIR="."
MODEL=""
VERBOSE=false
DRY_RUN=false
TASK_PROMPT=""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

show_help() {
    cat << 'EOF'
    Ralph Wiggum - AI Loop Technique for Claude Code

    Usage: ./ralph.sh [options] "Your prompt"

    Options:
      --max-iterations N       Stop after N iterations (default: 50)
        --completion-promise STR Phrase that signals done (default: "COMPLETE")
          --prompt-file FILE       Use a markdown file as the prompt
            --working-dir DIR        Set working directory
              --model MODEL            Specify model (sonnet, opus, haiku)
                --verbose                Show iteration numbers
                  --dry-run                Preview without executing
                    --help                   Show this help

                    Examples:
                      ./ralph.sh "Build a hello world API. Output COMPLETE when done."
                        ./ralph.sh --prompt-file PROMPT.md --max-iterations 20
                          ./ralph.sh --model opus "Complex task requiring deeper reasoning"

                          EOF
                          }

                          log_info() {
                              echo -e "${BLUE}[Ralph]${NC} $1"
                              }

                              log_success() {
                                  echo -e "${GREEN}[Ralph]${NC} $1"
                                  }

                                  log_warning() {
                                      echo -e "${YELLOW}[Ralph]${NC} $1"
                                      }

                                      log_error() {
                                          echo -e "${RED}[Ralph]${NC} $1"
                                          }

                                          # Parse arguments
                                          while [[ $# -gt 0 ]]; do
                                              case $1 in
                                                      --max-iterations)
                                                                  MAX_ITERATIONS="$2"
                                                                              shift 2
                                                                                          ;;
                                                                                                  --completion-promise)
                                                                                                              COMPLETION_PROMISE="$2"
                                                                                                                          shift 2
                                                                                                                                      ;;
                                                                                                                                              --prompt-file)
                                                                                                                                                          PROMPT_FILE="$2"
                                                                                                                                                                      shift 2
                                                                                                                                                                                  ;;
                                                                                                                                                                                          --working-dir)
                                                                                                                                                                                                      WORKING_DIR="$2"
                                                                                                                                                                                                                  shift 2
                                                                                                                                                                                                                              ;;
                                                                                                                                                                                                                                      --model)
                                                                                                                                                                                                                                                  MODEL="$2"
                                                                                                                                                                                                                                                              shift 2
                                                                                                                                                                                                                                                                          ;;
                                                                                                                                                                                                                                                                                  --verbose)
                                                                                                                                                                                                                                                                                              VERBOSE=true
                                                                                                                                                                                                                                                                                                          shift
                                                                                                                                                                                                                                                                                                                      ;;
                                                                                                                                                                                                                                                                                                                              --dry-run)
                                                                                                                                                                                                                                                                                                                                          DRY_RUN=true
                                                                                                                                                                                                                                                                                                                                                      shift
                                                                                                                                                                                                                                                                                                                                                                  ;;
                                                                                                                                                                                                                                                                                                                                                                          --help)
                                                                                                                                                                                                                                                                                                                                                                                      show_help
                                                                                                                                                                                                                                                                                                                                                                                                  exit 0
                                                                                                                                                                                                                                                                                                                                                                                                              ;;
                                                                                                                                                                                                                                                                                                                                                                                                                      *)
                                                                                                                                                                                                                                                                                                                                                                                                                                  TASK_PROMPT="$1"
                                                                                                                                                                                                                                                                                                                                                                                                                                              shift
                                                                                                                                                                                                                                                                                                                                                                                                                                                          ;;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              esac
                                                                                                                                                                                                                                                                                                                                                                                                                                                              done
                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Validate inputs
                                                                                                                                                                                                                                                                                                                                                                                                                                                              if [[ -z "$PROMPT_FILE" && -z "$TASK_PROMPT" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log_error "Error: Provide a prompt or --prompt-file"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      show_help
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          exit 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if [[ -n "$PROMPT_FILE" && ! -f "$PROMPT_FILE" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log_error "Error: Prompt file not found: $PROMPT_FILE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  exit 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # Change to working directory
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  cd "$WORKING_DIR"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # Build the prompt
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if [[ -n "$PROMPT_FILE" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      PROMPT=$(cat "$PROMPT_FILE")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          PROMPT="$TASK_PROMPT"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # Build claude command
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          CLAUDE_CMD="claude -p"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if [[ -n "$MODEL" ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              CLAUDE_CMD="$CLAUDE_CMD --model $MODEL"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Dry run mode
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if [[ "$DRY_RUN" == true ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log_info "=== DRY RUN ==="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      log_info "Max iterations: $MAX_ITERATIONS"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          log_info "Completion promise: $COMPLETION_PROMISE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log_info "Working directory: $(pwd)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log_info "Model: ${MODEL:-default}"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      log_info "Prompt:"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          echo "$PROMPT"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              exit 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Main loop
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log_info "Starting Ralph Wiggum loop..."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log_info "Max iterations: $MAX_ITERATIONS"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              log_info "Looking for: $COMPLETION_PROMISE"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              iteration=0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              while [[ $iteration -lt $MAX_ITERATIONS ]]; do
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ((iteration++))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if [[ "$VERBOSE" == true ]]; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log_info "=== Iteration $iteration/$MAX_ITERATIONS ==="
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Run Claude and capture output
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  output=$(echo "$PROMPT" | $CLAUDE_CMD 2>&1) || true
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "$output"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              # Check for completion
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if echo "$output" | grep -q "$COMPLETION_PROMISE"; then
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  log_success "Task completed after $iteration iteration(s)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          exit 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              fi
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      done
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      log_warning "Reached max iterations ($MAX_ITERATIONS) without completion"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      exit 1
